apiVersion: v1
kind: ConfigMap
metadata:
  name: global-config
data:
  # property-like keys; each key maps to a simple value
  CURRENCY_EXCHANGE_SERVICE_URI: http://currency-exchange
  namespace: default