FROM openjdk:17-jdk-slim
COPY target/currency-conversion-microservice-0.0.11-SNAPSHOT.jar currency-conversion-microservice-0.0.11-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/currency-conversion-microservice-0.0.11-SNAPSHOT.jar"]

