FROM openjdk:17-jdk-slim
COPY target/currency-exchange-service-0.0.11-SNAPSHOT.jar currency-exchange-service-0.0.11-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/currency-exchange-service-0.0.11-SNAPSHOT.jar"]
